### PR TITLE
Switch project deps management to `poetry`

### PR DESCRIPTION
**Pull request by shady-ti**

### CODE REVIEW

**Comment by shady-ti** [comment]
If this PR is a go, I'll update the commit messages first

**Comment by xnetcat** [comment]
Don't remove `scripts/build.py`. It's used for building executables on release

https://github.com/spotDL/spotdl-v4/blob/master/.github/workflows/python-publish.yml

**Comment by shady-ti** [comment]
THe tests will nedd to be modified to use poetry too.

**Comment by xnetcat** [comment]
> THe tests will nedd to be modified to use poetry too.

Any progress on the tests?

**Comment by shady-ti** [comment]
oh forgot bout this

**Comment by shady-ti** [comment]
tests should be fixed now

**Comment by xnetcat** [comment]
> tests should be fixed now
> 
> It technically should, manually running the command on my shell works but github still runs the master branch actions, not sure how to check if it runs on github

https://github.com/nektos/act

**Pull request merged**
